########################################################################
#                                                                      #
# David Fuller                                                         #
#                                                                      #
# Divination Card Rewards for Loot Filter Creator for Path of Exile    #
#                                                                      #
# Created on 2016-11-22                                                #
#                                                                      #
########################################################################

divinationRewards = []
divinationRewards.append(" ")                                          # 0
divinationRewards.append(" = 5 for 3 Exalted\n")                       # 1
divinationRewards.append(" = 8 for unique Shavronne Item\n")           # 2
divinationRewards.append(" = 13 for corrupted Voltaxic Rift\n")        # 3
divinationRewards.append(" = 10 for Colosseum Map\n")                  # 4
divinationRewards.append(" = 11 for corrupted level 4 Enhance\n")      # 5
divinationRewards.append(" = 9 for unique dagger\n")                   # 6
divinationRewards.append(" = 5 for corrupted Doryani's Fist\n")        # 7
divinationRewards.append(" = 12 for corrupted Mjolner\n")              # 8
divinationRewards.append(" = 5 for unique axe\n")                      # 9
divinationRewards.append(" = 9 for Maligaro's Virtuosity\n")           # 10
divinationRewards.append(" = 3 for The Goddess Bound\n")               # 11
divinationRewards.append(" = 7 for corrupted unique ring\n")           # 12
divinationRewards.append(" = 4 for unique body armour\n")              # 13
divinationRewards.append(" = 4 for a map\n")                           # 14
divinationRewards.append(" = 6 for 6-link Harbinger Bow\n")            # 15
divinationRewards.append(" = 8 for corrupted Voll's Devotion\n")       # 16
divinationRewards.append(" = 6 for unique Beyond item\n")              # 17
divinationRewards.append(" = 4 for magic life armour\n")               # 18
divinationRewards.append(" = 1 for ten Cartographer's Chisels\n")      # 19
divinationRewards.append(" = 3 for Tier 5 map\n")                      # 20
divinationRewards.append(" = 13 for level 21 spell gem\n")             # 21
divinationRewards.append(" = 3 for Vaal Orb\n")                        # 22
divinationRewards.append(" = 6 for 6-link Astral Plate\n")             # 23
divinationRewards.append(" = 11 for 6-link body armour\n")             # 24
divinationRewards.append(" = 1 for five Chaos Orbs\n")                 # 25
divinationRewards.append(" = 9 for Doryani's Fist\n")                  # 26
divinationRewards.append(" = 9 for five Regal Orbs\n")                 # 27
divinationRewards.append(" = 8 for Rigwald's Curse\n")                 # 28
divinationRewards.append(" = 6 for 6-link body armour\n")              # 29
divinationRewards.append(" = 6 for 6-link staff\n")                    # 30
divinationRewards.append(" = 4 for Mon'tregul's Grasp\n")              # 31
divinationRewards.append(" = 5 for Deaht's Hand\n")                    # 32
divinationRewards.append(" = 5 for rare Body Armour\n")                # 33
divinationRewards.append(" = 8 for corrupted Atziri's Disfavour\n")    # 34
divinationRewards.append(" = 7 for 23% support gem\n")                 # 35
divinationRewards.append(" = 8 for Headhunter\n")                      # 36
divinationRewards.append(" = 9 for Doedre Item\n")                     # 37
divinationRewards.append(" = 2 for 20% Mirror Arrow\n")                # 38
divinationRewards.append(" = 4 for Coruscating Elixir\n")              # 39
divinationRewards.append(" = 11 for level 4 Empower\n")                # 40
divinationRewards.append(" = 8 for Divination Distillate\n")           # 41
divinationRewards.append(" = 8 for level 19 skill gem\n")              # 42
divinationRewards.append(" = 5 for unique Granite Flask\n")            # 43
divinationRewards.append(" = 7 for 6-link Holy Chainmail\n")           # 44
divinationRewards.append(" = 5 for 5x Currency\n")                     # 45
divinationRewards.append(" = 8 for corrupted unique Map\n")            # 46
divinationRewards.append(" = 4 for magic Vivid Crimson Jewel\n")       # 47
divinationRewards.append(" = 6 for level 3 Enlighten\n")               # 48
divinationRewards.append(" = 7 for 6-link Vaal Regalia\n")             # 49
divinationRewards.append(" = 6 for corrupted rare Map\n")              # 50
divinationRewards.append(" = 5 for corrupted Romira's banquet\n")      # 51
divinationRewards.append(" = 11 for corrupted Headhunter\n")           # 52
divinationRewards.append(" = 5 for corrupted Drillneck\n")             # 53
divinationRewards.append(" = 5 for 5-link Staff\n")                    # 54
divinationRewards.append(" = 7 for Varunastra\n")                      # 55
divinationRewards.append(" = 6 for level 20 gem\n")                    # 56
divinationRewards.append(" = 5 for Divination Card\n")                 # 57
divinationRewards.append(" = 3 for Gemcutter's Prism\n")               # 58
divinationRewards.append(" = 3 for 20% Gem\n")                         # 59
divinationRewards.append(" = 4 for corrupted unique Sword\n")          # 60
divinationRewards.append(" = 9 for level 20 Support Gem\n")            # 61
divinationRewards.append(" = 5 for unique Nightmare Bascinet\n")       # 62
divinationRewards.append(" = 8 for unique Gold Ring\n")                # 63
divinationRewards.append(" = 6 for 20% Summon Raging Spirit\n")        # 64
divinationRewards.append(" = 11 for The Harvest\n")                    # 65
divinationRewards.append(" = 4 for Sacrifice Fragment\n")              # 66
divinationRewards.append(" = 9 for Lifesprig\n")                       # 67
divinationRewards.append(" = 2 for unique Two-Stone Ring\n")           # 68
divinationRewards.append(" = 12 for Exalted Orb\n")                    # 69
divinationRewards.append(" = 5 for corrupted unique Prismatic Ring\n") # 70
divinationRewards.append(" = 9 for Mirror of Kalandra\n")              # 71
divinationRewards.append(" = 5 for unique Ring\n")                     # 72
divinationRewards.append(" = 9 for Tabula Rasa\n")                     # 73
divinationRewards.append(" = 9 for Taste of Hate\n")                   # 74
divinationRewards.append(" = 8 for unique Bow\n")                      # 75
divinationRewards.append(" = 3 for The Taming\n")                      # 76
divinationRewards.append(" = 10 for House of Mirrors\n")               # 77
divinationRewards.append(" = 4 for The Whispering Ice\n")              # 78
divinationRewards.append(" = 4 for magic Seraphim's Armour\n")         # 79
divinationRewards.append(" = 6 for 10x Vaal Orb\n")                    # 80
divinationRewards.append(" = 4 for unique Item\n")                     # 81
divinationRewards.append(" = 9 for magic Merciless One-Hand Weapon\n") # 82
divinationRewards.append(" = 5 for magic Bloodthirsty Eternal Sword\n")# 83
divinationRewards.append(" = 8 for Kaom's heart\n")                    # 84
divinationRewards.append(" = 7 for rare Two-Stone Ring\n")             # 85
divinationRewards.append(" = 3 for Mortal Hope\n")                     # 86
divinationRewards.append(" = 10 for Atziri's Disfavour\n")             # 87
divinationRewards.append(" = 12 for corrupted Midnight Bargai\n")      # 88
divinationRewards.append(" = 2 for unique Crystal Sceptre\n")          # 89
divinationRewards.append(" = 5 for unique Lioneye Item\n")             # 90
divinationRewards.append(" = 6 for magic Ring of Bameth\n")            # 91
divinationRewards.append(" = 8 Tier 15 Map\n")                         # 92
divinationRewards.append(" = 2 for Rare Jewellery\n")                  # 93
divinationRewards.append(" = 5 for 3x Orb of Fusing\n")                # 94
divinationRewards.append(" = 7 for 20x Orb of Fusing\n")               # 95
divinationRewards.append(" = 9 for 10x Stacked Deck\n")                # 96
divinationRewards.append(" = 5 for Sire of Shards\n")                  # 97
divinationRewards.append(" = 5 for unique Agate Amulet\n")             # 98
divinationRewards.append(" = 16 for Eyes of the Greatwolf\n")          # 99
divinationRewards.append(" = 5 for corrupted unique Shield\n")         # 100
divinationRewards.append(" = 4 for magic Merciless Two-Handed Weapon\n")# 101
divinationRewards.append(" = 6 for Prismatic Ring\n")                  # 102
divinationRewards.append(" = 6 for Fertile Mind\n")                    # 103
divinationRewards.append(" = 6 for Death's Oath\n")                    # 104
divinationRewards.append(" = 8 for Shavronne's Wrappings\n")           # 105
divinationRewards.append(" = 6 for corrupted Le Heup of All\n")        # 106
divinationRewards.append(" = 6 for Alpha's howl\n")                    # 107
divinationRewards.append(" = 9 for Pledge of Hands\n")                 # 108
divinationRewards.append(" = 5 for unique Unset Ring\n")               # 109
divinationRewards.append(" = 9 for corrupted Blood of Corruption\n")   # 110
divinationRewards.append(" = 8 for corrupte Kaom's Heart\n")           # 111
divinationRewards.append(" = 10 for magic Perandus' Gold Ring\n")      # 112
divinationRewards.append(" = 16 for Atziri's Acuity\n")                # 113
divinationRewards.append(" = 4 for magic malicious Gemini Claw\n")     # 114
divinationRewards.append(" = 8 for Chaos Orb\n")                       # 115
divinationRewards.append(" = 9 for Strand Map\n")                      # 116
divinationRewards.append(" = 8 for Rat's Nest\n")                      # 117
divinationRewards.append(" = 3 for Ventor's Gamble\n")                 # 118
divinationRewards.append(" = 7 for magic Runic One-Hand Weapon\n")     # 119
divinationRewards.append(" = 9 for Wake of Destruction\n")             # 120
divinationRewards.append(" = 8 for Carcass Jack\n")                    # 121
divinationRewards.append(" = 3 for 40x Scroll of Wisdom\n")            # 122
divinationRewards.append(" = 7 for Mao Kun\n")                         # 123
divinationRewards.append(" = 11 for 10x Divine Orb\n")                 # 124
divinationRewards.append(" = 4 for magic Vivid Jewel\n")               # 125
divinationRewards.append(" = 3 for magic Unassailable Amulet\n")       # 126
divinationRewards.append(" = 7 for corrupted The Whispering Ice\n")    # 127
divinationRewards.append(" = 9 for Soul Taker\n")                      # 128
divinationRewards.append(" = 4 for magic Dictator's Prophecy Wand\n")  # 129
divinationRewards.append(" = 4 for unique Agnerod Staff\n")            # 130
divinationRewards.append(" = 6 for 20% Minion Gem\n")                  # 131
divinationRewards.append(" = 7 for Rise of the Phoenix\n")             # 132
divinationRewards.append(" = 4 for magic Surgeon's Flask\n")           # 133
divinationRewards.append(" = 4 for Tier 14 Map\n")                     # 134
divinationRewards.append(" = 3 for 7x Orb of Alchemy\n")               # 135
divinationRewards.append(" = 8 for corrupted Shavronne's Revelation\n")# 136
divinationRewards.append(" = 7 for x3 Chaos Orb\n")                    # 137
divinationRewards.append(" = 2 for corrupted Kaom's Roots\n")          # 138
divinationRewards.append(" = 5 for Storm Cloud\n")                     # 139
divinationRewards.append(" = 10 for unique League-Specific Item\n")    # 140
divinationRewards.append(" = 6 for unique Staff\n")                    # 141
divinationRewards.append(" = 4 for corrupted unique Wand\n")           # 142
divinationRewards.append(" = 7 for Voltaxic Rift\n")                   # 143
divinationRewards.append(" = 7 for corrupted Vaults of Atziri\n")      # 144
divinationRewards.append(" = 7 for corrupted rare Tier 15 Map\n")      # 145
divinationRewards.append(" = 3 for corrupted Pacifism\n"     )         # 146
divinationRewards.append(" = 8 for magic Gemini Claw of Celebration\n")# 147
divinationRewards.append(" = 9 for magic Merciless Weapon\n")          # 148
divinationRewards.append(" = 7 for 10x Gemcutter's Prism\n")           # 149
divinationRewards.append(" = 8 for unique Nemesis Item\n")             # 150
divinationRewards.append(" = 7 for Song of Sirens\n")                  # 151
divinationRewards.append(" = 5 for 10x Orb of Regret\n")               # 152
divinationRewards.append(" = 6 for Lioneye's Vision\n")                # 153
divinationRewards.append(" = 1 for random turn in\n")                  # 154
divinationRewards.append(" = 9 for 20% Vaal Gem\n")                    # 155
divinationRewards.append(" = 4 for corrupted rare Amulet\n")           # 156
divinationRewards.append(" = 6 for 6-link Coronal Maul\n")             # 157
divinationRewards.append(" = 12 for Crown of Eyes\n")                  # 158
divinationRewards.append(" = 11 for corrupted level 4 Enlighten\n")    # 159
divinationRewards.append(" = 8 for magic Weapon of Crafting\n")        # 160
divinationRewards.append(" = 7 for Windripper\n")                      # 161
divinationRewards.append(" = 5 for Rigwald Item\n")                    # 162
divinationRewards.append(" = 3 for Hyaon's Fury\n")                    # 163
divinationRewards.append(" = 8 for 10x Chaos Orb\n")                   # 164
